### ISSUE TITLE
Wrong key italian translation

### ISSUE THREAD

**Issue by GioviQ** [dotnet/EntityFramework.Docs.it-it#8]
Keys in the left side menu of the page must be translated in Italian as "Chiavi" and not as "Tasti", because "Tasti" are the keyboard keys.

[Immetti qui i commenti]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: d0a084df-15c4-ab25-26ca-83c8bdf6f026
* Version Independent ID: f1fba5b2-eb2e-da0a-fce0-d492855c1777
* Content: [Chiavi-EF Core](https://docs.microsoft.com/it-it/ef/core/modeling/keys?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/keys.md](https://github.com/dotnet/EntityFramework.Docs.it-it/blob/live/entity-framework/core/modeling/keys.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by JasonCard** [comment]
@GioviQ @dennybiasiolli @Rick-Anderson Thank you for raising this feedback. I'm following up with our loc vendor.

**Comment by JasonCard** [comment]
@GioviQ This issue is now fixed :)
